sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
services:
- postgresql
- redis
script:
- rake db:test:prepare
- rake
deploy:
  - provider: cloud66
    redeployment_hook: $CLOUD66_STAGING_REDEPLOYMENT_HOOK
    on:
      all_branches: true
      repo: mlvk/in-spiritus
  - provider: cloud66
    redeployment_hook: $CLOUD66_PRODUCTION_REDEPLOYMENT_HOOK
    on:
      all_branches: true
      condition: -n $TRAVIS_TAG
addons:
  hosts:
    - db
