default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: in_spiritus

test:
  <<: *default
  database: in_spiritus_test

staging:
  <<: *default
  database: <%= ENV["POSTGRESQL_DATABASE"] %>
  host: <%= ENV["POSTGRESQL_ADDRESS"] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>

production:
  <<: *default
  database: <%= ENV["POSTGRESQL_DATABASE"] %>
  host: <%= ENV["POSTGRESQL_ADDRESS"] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
