default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: db
  pool: 5

development:
  <<: *default
  database: in_spiritus

test:
  <<: *default
  database: in_spiritus_test

staging:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

production:
  <<: *default
  database: <%= ENV["POSTGRESQL_DATABASE"] %>
  host: <%= ENV["POSTGRESQL_ADDRESS"] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
